### ISSUE TITLE
port consolepaint to c# syntex

### ISSUE THREAD

**Issue by ghost** [RealDoigt/ConsolePaint#3]
i'll look into formatting the console paint library to be portable to vanilla c# syntex so people don't have to fully rely on boo's lang library.

**Comment by RealDoigt** [comment]
Even though it is written using Boo, this library is already written using C# convention and follows the best practices taught in college circles. The point of writing in Boo is to access its advanced features and make C# developers be able to benefit of those through this library. Also, judging from looking at the code you've written that you've shown me, your code itself usually doesn't respect C# best practices in regards to spelling, naming conventions and general algorithms. Porting the library to C# is not only a huge and time consuming endeavour, but it is also out of your current skill range. Finally, keep in mind this library is a hobby project for fun, so the usage of Boo is not inappropriate. Therefore, for the aforementioned reasons, I'm closing this issue.

**Comment by ghost** [comment]
_understandable_
